### ISSUE TITLE
Need Help in installation

### ISSUE THREAD

**Issue by harshaa1590** [jcroav/room-reservation#9]
Hello Team, 
Am new to this and have downloaded the zip and got it extracted locally. like other examples in Github am unable to look for the gulp or able to package it to an sppkg file and add it to my SP appcatalog. could someone advise me what is that i am missing. what is the procedure in this scenario to go about.

I know this app is available in appstore however that does not have the **html { overflow:scroll; }**, hence i have to go through this. 

Kindly advise / point me to any url which can guide me. 

Thanks a ton.

**Comment by mrjims1** [comment]
This is what I did.
After downloading and extracting. 
I opened it with Visual Studio.
Made my changes.
Published it in Visual Studio which creates the Room-Reservation.app file.
I then uploaded the file to SP Appcatalog.

**Comment by harshaa1590** [comment]
Thank you, let me give it a try !!
